### ISSUE TITLE
OUT_OF_RANGE_FEE error

### ISSUE THREAD

**Issue by danikula** [0xs34n/starknet.js-workshop#4]
When I try to launch example `node index.js` I got error
```
starknet.js-workshop % node index.js 
Reading Argent Account Contract...
Reading ERC20 Contract...
Deployment Tx - Account Contract to StarkNet...
Waiting for Tx to be Accepted on Starknet - Argent Account Deployment...
Invoke Tx - Initialize Argnet Account...
/Users/danik/Work/starknet/starknetjs/starknet.js-workshop/node_modules/starknet/dist/provider/default.js:210
                            throw new Error(data.code + ": " + data.message);
                                  ^

Error: StarknetErrorCode.OUT_OF_RANGE_FEE: max_fee must be bigger than 0.
0 >= 0
    at Provider.<anonymous> (/Users/danik/Work/starknet/starknetjs/starknet.js-workshop/node_modules/starknet/dist/provider/default.js:210:35)
    at step (/Users/danik/Work/starknet/starknetjs/starknet.js-workshop/node_modules/starknet/dist/provider/default.js:44:23)
    at Object.throw (/Users/danik/Work/starknet/starknetjs/starknet.js-workshop/node_modules/starknet/dist/provider/default.js:25:53)
    at rejected (/Users/danik/Work/starknet/starknetjs/starknet.js-workshop/node_modules/starknet/dist/provider/default.js:17:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.2.0
```

**Comment by Qupday** [comment]
hi  Do you solve this exception so far?

**Comment by xiaojiu1020** [comment]
hi Do you solve this exception so far? I have the same problem

**Comment by ivpavici** [comment]
Hi, 
This issue should be fixed with latest introduced changes!
